apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
spec:
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi
        image: catalogapi:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MongoDBSettings__Host
          value: mongodb-service
        - name: MongoDBSettings__Password
          valueFrom:
            secretKeyRef:
              name: catalogapi-secrets
              key: mongodb-password
        livenessProbe:
          httpGet:
            path: /healthcheck/live
            port: 80
        readinessProbe:
          httpGet:
            path: /healthcheck/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  type: LoadBalancer
  selector:
    app: catalogapi
  ports:
  - port: 80
    targetPort: 80
  